spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-service
          uri: ${AUTH_ROUTE_URI:http://localhost:8040}
          predicates:
            - Path=/auth/**
        - id: employee-service
          uri: ${EMPLOYEE_ROUTE_URI:http://localhost:8050}
          predicates:
            - Path=/employee/**
        - id: project-service
          uri: ${PROJECT_ROUTE_URI:http://localhost:8060}
          predicates:
            - Path=/project/**
        - id: shift-service
          uri: ${SHIFT_ROUTE_URI:http://localhost:8070}
          predicates:
            - Path=/shift/**
        - id: sprint-service
          uri: ${SPRINT_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/sprint/**
            - Path=/task/**
