server:
  port: 8888
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://D:\Mega\Університет\3 курс\Конструювання програмного забезпечення\Курсова\config-repo
          git:
            uri: file:///D:/Mega/Університет/3 курс/Конструювання програмного забезпечення/Курсова/config-repo
  #          uri: https://github.com/BranetE/config-repo
  application:
    name: config-server
